# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: work-flow

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.action_path }}
      - run: echo ${{ github.workspace }}
      - run: echo pwd
      - run: npm start
