# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: work-flow

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${ secrets.npm_token }
      GITHUB_TOKEN: ${ secrets.GITHUB_TOKEN }
    steps:
      - run: echo 'Hi'
      - run: echo ${env.GITHUB_TOKEN}
      - run: echo ${{ env.GITHUB_TOKEN}}
